LXI H,2000 //take memory adress 2000 in H
MOV A,M //M TAKE DATA FROM H ADDRESS AND MOVE TO A
INX H	 // INCRESE HL REGISTER PAIR TO NEXT VALUE
MOV B,M //M TAKE NEW DATA AND STORE IN B
ADD B
INX H
STA 2024

HLT