// DATA STORE IN MEMORY

LXI H,2000 //take memory adress 2000 in H
MVI M,08H // AT 2000 STORE 08 NUMBER
INX H
MVI M,04H // AT 2001 STORE 04 NUMBER
LXI H,2000 // REDEFINE HL

// DATA TAKE FROM MEMORY AND DO ADDITION

MOV A,M //M TAKE DATA FROM H ADDRESS AND MOVE TO A
INX H	 // INCRESE HL REGISTER PAIR TO NEXT VALUE
MOV B,M //M TAKE NEW DATA AND STORE IN B
ADD B
INX H
MOV M,A //STORE ANS IN NEW MEMORY

HLT